version: '3.8'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kanaha
      - POSTGRES_PASSWORD=kanaha
      - POSTGRES_DB=bst_django_dev
    ports:
      - "5435:5432"

volumes:
  postgres_data: