# pull official base image
FROM python:3.9.10-alpine

# set work directory
WORKDIR /usr/src/app/backend

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN echo "http://dl-8.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
# install psycopg2 dependencies
# RUN apk add --no-cache postgresql-dev python3-dev libstdc++ && \
#     apk add --no-cache g++ && \
#     ln -s /usr/include/locale.h /usr/include/xlocale.h && \
#     pip3 install numpy && \
#     pip3 install pandas

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev g++ py3-numpy py3-pandas
ENV PYTHONPATH=/usr/lib/python3.9/site-packages





# install dependencies
RUN pip install --upgrade pip
RUN pip install --upgrade cython
COPY ./requirements.txt /usr/src/app/backend
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh


# copy project
COPY . /usr/src/app/backend

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]