# Generated by Django 4.0.3 on 2023-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
