# Generated by Django 4.0.3 on 2022-04-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_purchaserequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereqproductrel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasereqproductrel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchasereqproductrel',
            name='unit',
        ),
        migrations.AddField(
            model_name='purchasereqproductrel',
            name='provisionProduct',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logistic.provisionproductrel'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='ref',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
