# Generated by Django 4.0.3 on 2022-04-06 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_remove_purchasereqproductrel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
