# Generated by Django 4.0.3 on 2022-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_alter_purchasereqproductrel_purchaserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='approved_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
