# Generated by Django 4.0.3 on 2022-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_alter_purchaserequest_approved_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
