# Generated by Django 4.0.3 on 2022-04-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0010_alter_provision_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ('id',), 'permissions': (('approve_purchaserequest', 'Can approve purchase request'),)},
        ),
    ]
