# Generated by Django 4.0.3 on 2022-04-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_alter_purchaserequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=220)),
            ],
        ),
    ]
