# Generated by Django 4.0.3 on 2022-04-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit',
            new_name='base_unit',
        ),
    ]
