# Generated by Django 4.0.3 on 2022-04-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0016_unitconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_converions', to='logistic.product'),
        ),
    ]
