# Generated by Django 4.0.3 on 2022-05-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0017_alter_unitconversion_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='logistic.product'),
        ),
    ]
