# Generated by Django 4.0.3 on 2022-05-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def defaultValueUnit(apps, schema_editor):

        ProvisionProductRel = apps.get_model("logistic", "ProvisionProductRel")

        PurchaseReqProductRel = apps.get_model("logistic", "PurchaseReqProductRel")
        
        for purchaseReqProductRel in PurchaseReqProductRel.objects.all():
            provisionProduct = ProvisionProductRel.objects.get(id=purchaseReqProductRel.provisionProduct.id)
            purchaseReqProductRel.unit = provisionProduct.unit
            purchaseReqProductRel.save()

    def defaultValueQuantity(apps, schema_editor):

        ProvisionProductRel = apps.get_model("logistic", "ProvisionProductRel")

        PurchaseReqProductRel = apps.get_model("logistic", "PurchaseReqProductRel")
        
        for purchaseReqProductRel in PurchaseReqProductRel.objects.all():
            provisionProduct = ProvisionProductRel.objects.get(id=purchaseReqProductRel.provisionProduct.id)
            purchaseReqProductRel.quantity = provisionProduct.quantity
            purchaseReqProductRel.save()


    dependencies = [
        ('logistic', '0019_alter_provisionproductrel_unit'),
    ]

    operations = [
        migrations.RunPython(defaultValueUnit, atomic =False),
        migrations.RunPython(defaultValueQuantity, atomic =False),
        migrations.AddField(
            model_name='purchasereqproductrel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereqproductrel',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.unit'),
        ),
    ]
