# Generated by Django 4.0.3 on 2022-05-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0020_purchasereqproductrel_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
