# Generated by Django 4.0.3 on 2022-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0021_alter_provision_approved_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code_postal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='register_number',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
