# Generated by Django 4.0.3 on 2022-05-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0022_supplier_address_supplier_city_supplier_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ref',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('1', 'NEW'), ('999', 'DELIVERED')], default='1', max_length=220, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='purchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='logistic.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderProductRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.FloatField(blank=True, null=True)),
                ('purchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrderProducts', to='logistic.purchaseorder')),
                ('purchaseProduct', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logistic.purchasereqproductrel')),
            ],
        ),
    ]
