# Generated by Django 4.0.3 on 2022-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0023_purchaseorder_ref_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
