# Generated by Django 4.0.3 on 2022-08-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0027_stock_store_receipt_do_receipt_invoice_receipt_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptproductrel',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptProducts', to='logistic.receipt'),
        ),
    ]
