# Generated by Django 4.0.3 on 2022-08-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0028_alter_receiptproductrel_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptproductrel',
            old_name='purchaseOrderProductRel',
            new_name='purchaseOrderProduct',
        ),
    ]
