# Generated by Django 4.0.3 on 2022-08-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0029_rename_purchaseorderproductrel_receiptproductrel_purchaseorderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionproductrel',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchasereqproductrel',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiptproductrel',
            name='quantity_accepted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiptproductrel',
            name='quantity_receipt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='logistic.store'),
        ),
    ]
