# Generated by Django 4.0.3 on 2022-08-17 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0030_alter_provisionproductrel_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
