# Generated by Django 4.0.3 on 2022-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0032_alter_receiptproductrel_conformity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='do',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
