# Generated by Django 4.0.3 on 2022-10-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0033_alter_receipt_do_alter_receipt_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptproductrel',
            name='purchaseOrderProduct',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='received', to='logistic.purchaseorderproductrel'),
        ),
    ]
