# Generated by Django 4.0.3 on 2022-10-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0034_alter_receiptproductrel_purchaseorderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('old_quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('old_price', models.FloatField(null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_init', to='logistic.stock')),
            ],
        ),
    ]
