# Generated by Django 4.0.3 on 2022-10-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0036_alter_stockout_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('0', 'in'), ('1', 'out'), ('2', 'init')], max_length=22, verbose_name='movement')),
                ('movement_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stockin',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterModelOptions(
            name='stockinit',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterModelOptions(
            name='stockout',
            options={'ordering': ('created_on',)},
        ),
    ]
