# Generated by Django 4.0.3 on 2022-10-19 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0037_stockmovement_alter_stockin_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stockmovement',
            unique_together={('movement_type', 'movement_id')},
        ),
    ]
