# Generated by Django 4.0.3 on 2022-10-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0039_stockmovement_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='ref',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('0', 'in'), ('1', 'out'), ('2', 'init')], max_length=22, verbose_name='movement_type'),
        ),
    ]
