# Generated by Django 4.0.3 on 2022-10-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0040_transfer_ref_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='ref',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockinit',
            name='ref',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='ref',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
