# Generated by Django 4.0.3 on 2022-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0041_stockin_ref_stockinit_ref_stockout_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterField(
            model_name='stockout',
            name='target',
            field=models.CharField(choices=[('2', 'TRANSFER'), ('3', 'TO_PROJECT')], max_length=22, verbose_name='target'),
        ),
    ]
