# Generated by Django 4.0.3 on 2022-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0043_alter_stockmovement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='target_detail',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
