# Generated by Django 4.0.3 on 2022-10-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0044_stockout_target_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('-created_on',)},
        ),
    ]
