# Generated by Django 4.0.3 on 2022-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0045_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinit',
            name='old_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinit',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
