# Generated by Django 4.0.3 on 2023-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0047_stockin_note_stockout_note_alter_stock_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
