# Generated by Django 4.0.3 on 2023-02-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0049_proformainvoicerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoicerequest',
            name='status',
            field=models.CharField(choices=[('1', 'NEW'), ('999', 'DELIVERED')], default='1', max_length=220, verbose_name='status'),
        ),
    ]
