# Generated by Django 4.0.3 on 2023-02-21 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logistic.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0050_proformainvoicerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, null=True, unique=True)),
                ('proformaSupplierRef', models.CharField(max_length=50, null=True, unique=True)),
                ('tax_including', models.BooleanField(default=True)),
                ('tax_rate', models.FloatField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='proformainvoicerequest',
            name='status',
            field=models.CharField(choices=[('1', 'NEW'), ('999', 'RECEIVED')], default='1', max_length=220, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='ProformaInvoiceProductRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('proformaInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistic.proformainvoice')),
                ('proformaInvoiceRequestProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.proformainvoicerequestproductrel')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaInvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=logistic.models.user_directory_path)),
                ('proformaInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='logistic.proformainvoice')),
            ],
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='proformaRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformaInvoice', to='logistic.proformainvoicerequest'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.supplier'),
        ),
    ]
