# Generated by Django 4.0.3 on 2023-02-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0051_proformainvoice_alter_proformainvoicerequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='proformaSupplierRef',
        ),
    ]
