# Generated by Django 4.0.3 on 2023-02-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0054_alter_proformainvoicedocument_proformainvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='unit',
        ),
        migrations.AddField(
            model_name='transfer',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TransferProductRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistic.transfer')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.unit')),
            ],
        ),
    ]
