# Generated by Django 4.0.3 on 2023-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0055_remove_transfer_price_remove_transfer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('1', 'NEW'), ('999', 'COMPLETED')], default='1', max_length=220, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='source',
            field=models.CharField(choices=[('0', 'PURCHASE'), ('1', 'CASH_PURCHASE'), ('2', 'TRANSFER'), ('3', 'OTHER')], max_length=22, verbose_name='source'),
        ),
    ]
