# Generated by Django 4.0.3 on 2023-05-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0056_transfer_status_alter_stockin_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='received_on',
            field=models.DateTimeField(null=True),
        ),
    ]
