# Generated by Django 4.0.3 on 2023-05-15 08:49

from django.db import migrations, models
import django.db.models.deletion
import logistic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0057_transfer_received_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=logistic.models._upload_to)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='logistic.transfer')),
            ],
        ),
    ]
