# Generated by Django 4.0.3 on 2023-05-16 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logistic.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0058_transferdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, null=True, unique=True)),
                ('quantity', models.FloatField()),
                ('source', models.CharField(choices=[('0', 'PURCHASE'), ('1', 'CASH_PURCHASE'), ('2', 'TRANSFER'), ('3', 'OTHER')], max_length=22, verbose_name='source')),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('source_document', models.FileField(blank=True, null=True, upload_to=logistic.models._upload_to_stock_in)),
                ('stock_in_document', models.FileField(blank=True, null=True, upload_to=logistic.models._upload_to_stock_in)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockin',
            name='stock_in_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_in_products', to='logistic.stockindocument'),
        ),
    ]
