# Generated by Django 4.0.3 on 2023-05-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0059_stockindocument_stockin_stock_in_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockindocument',
            name='quantity',
        ),
    ]
