# Generated by Django 4.0.3 on 2023-05-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0063_alter_stockindocumentfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindocumentfile',
            name='stock_in_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='file', to='logistic.stockindocument'),
        ),
    ]
