# Generated by Django 4.0.3 on 2023-05-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0065_alter_stockindocumentfile_stock_in_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='stock_in_document',
        ),
        migrations.AddField(
            model_name='stockindocument',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_in_documents', to='logistic.store'),
        ),
        migrations.CreateModel(
            name='StockInDocumentProductRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='logistic.stockindocument')),
            ],
        ),
    ]
