# Generated by Django 4.0.3 on 2023-05-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0066_remove_stockin_stock_in_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindocumentproductrel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stockindocumentproductrel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.product'),
        ),
        migrations.AddField(
            model_name='stockindocumentproductrel',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stockindocumentproductrel',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.unit'),
        ),
    ]
