# Generated by Django 4.0.3 on 2023-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0067_stockindocumentproductrel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindocument',
            name='status',
            field=models.CharField(choices=[('1', 'NEW'), ('999', 'COMPLETED')], default='new', max_length=220, verbose_name='status'),
        ),
    ]
