# Generated by Django 4.0.3 on 2023-05-19 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logistic.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0069_alter_stockindocument_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOutDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, null=True, unique=True)),
                ('target', models.CharField(choices=[('3', 'TO_PROJECT'), ('4', 'OTHER')], max_length=22, verbose_name='TARGET')),
                ('target_detail', models.CharField(blank=True, max_length=220, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('1', 'NEW'), ('999', 'COMPLETED')], default='new', max_length=220, verbose_name='status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_out_documents', to='logistic.store')),
            ],
        ),
        migrations.CreateModel(
            name='StockOutDocumentProductRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.product')),
                ('stock_out_document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='logistic.stockoutdocument')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.unit')),
            ],
        ),
        migrations.CreateModel(
            name='StockOutDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=logistic.models._upload_to_stock_out)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('stock_out_document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='file', to='logistic.stockoutdocument')),
            ],
        ),
    ]
