# Generated by Django 4.0.3 on 2023-05-20 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0070_stockoutdocument_stockoutdocumentproductrel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='stockOutDocument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.stockoutdocument'),
        ),
    ]
