# Generated by Django 4.0.3 on 2023-06-04 12:58

from django.db import migrations, models
import django.db.models.deletion
import logistic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0071_stockout_stockoutdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=logistic.models._upload_receipt_to)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='logistic.receipt')),
            ],
        ),
    ]
