# Generated by Django 4.0.3 on 2023-06-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0072_receiptdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptdocument',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='logistic.receipt'),
        ),
    ]
