# Generated by Django 4.0.3 on 2023-06-07 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic', '0073_alter_receiptdocument_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='dropped_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provision_dropped_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provision',
            name='dropped_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provision',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
