# Generated by Django 4.0.3 on 2023-06-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0074_provision_dropped_by_provision_dropped_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='provision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='logistic.provision'),
        ),
    ]
