# Generated by Django 4.0.3 on 2023-06-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0075_alter_purchaserequest_provision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdocument',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='logistic.transfer'),
        ),
    ]
