# Generated by Django 4.0.3 on 2023-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0076_alter_transferdocument_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockout',
            name='target',
            field=models.CharField(choices=[('2', 'TRANSFER'), ('3', 'TO_PROJECT'), ('4', 'OTHER')], max_length=22, verbose_name='target'),
        ),
    ]
