# Generated by Django 4.0.3 on 2023-06-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0077_alter_stockout_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoutdocumentfile',
            name='stock_out_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='logistic.stockoutdocument'),
        ),
        migrations.AlterField(
            model_name='stockoutdocumentproductrel',
            name='stock_out_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistic.stockoutdocument'),
        ),
    ]
