# Generated by Django 4.0.3 on 2023-07-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0078_alter_stockoutdocumentfile_stock_out_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindocumentproductrel',
            name='stock_in_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistic.stockindocument'),
        ),
        migrations.AlterField(
            model_name='stockindocumentsourcefile',
            name='stock_in_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_file', to='logistic.stockindocument'),
        ),
    ]
