# Generated by Django 4.0.3 on 2023-07-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0079_alter_stockindocumentproductrel_stock_in_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindocumentfile',
            name='stock_in_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='logistic.stockindocument'),
        ),
    ]
