# Generated by Django 4.0.3 on 2023-07-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0081_alter_stockindocument_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockout',
            name='stockOutDocument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.stockoutdocument'),
        ),
    ]
