# Generated by Django 4.0.3 on 2024-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0082_alter_stockout_stockoutdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'NEW'), ('4', 'DROP'), ('9', 'APPROVED'), ('999', 'COMPLETED')], default='new', max_length=220, verbose_name='status'),
        ),
    ]
