# Generated by Django 4.0.3 on 2023-01-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('codePostal', models.CharField(max_length=20)),
            ],
        ),
    ]
