# Generated by Django 4.0.3 on 2023-01-18 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(null=True)),
                ('payment_target', models.CharField(choices=[('0', 'SUPPLIER'), ('1', 'CONTRACTOR'), ('2', 'EMPLOYEE')], max_length=22, verbose_name='target')),
                ('ref_target', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('0', 'CASH'), ('1', 'CHEQUE'), ('2', 'WIRE')], max_length=22, verbose_name='type')),
                ('payment_detail', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ref', models.IntegerField(blank=True, null=True)),
                ('bank', models.CharField(max_length=22)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
