# Generated by Django 4.0.3 on 2022-05-28 11:34

from django.db import migrations, models
from bst_django.utils import get_access_token

class Migration(migrations.Migration):


    def defaultPrivateKey(apps, schema_editor):

        Users = apps.get_model("user_control", "CustomUser")
        for user in Users.objects.all():
            print(user)
            access = get_access_token({"user_id": user.id, "user_username": user.username}, 99999)
            user.private_key = access
            user.save()

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(defaultPrivateKey, atomic =False),
        migrations.AddField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
